### ISSUE TITLE
How to access session attributes

### ISSUE THREAD

**Issue by cortilia** [PebbleTemplates/pebble-spring4#1]
Hi guys,

I have an help request. I'm using Pebble with SpringBoot. I know I can access the `HttpSession` from within the template. Then, is there any way to retrieve a session attribute from the template? 
If yes, please, can you post an example?

Best
Massimo

**Comment by ebussieres** [comment]
You can access any method of any object with pebble. Just try something like 

``
{{ session.getAttribute("attributeName") }}
``
or
``
{{ session.attribute("attributeName") }}
``

**Comment by cortilia** [comment]
Thanks a lot for answering
