### ISSUE TITLE
Cannot access form error helpers inside of a macro

### ISSUE THREAD

**Issue by Kirogo** [PebbleTemplates/pebble-spring4#2]
Hello,
I was trying to simplify the error handling on some of my forms, by adding a macro that could print every error linked to a field. The macro looked like : 
```{html}
{% macro formErrors(formName, fieldName) %}
    {% for err in getFieldErrors(formName, fieldName) %}
        {{ err }}<br/>
    {% endfor %}
{% endmacro %}
```
But returned nothing (while the macro's content were actually displaying the errors). I guess that getFieldErrors cannot be accessed from a macro, is that right ?

Cheers !

**Comment by ebussieres** [comment]
Macro doesn't have access to the same variables that the rest of the template has access to. So macro doesn't have access to the BindingResult spring variable in the context. If you want to make it generic, you can make something like this 

Declare a formErrors.html file containing
```
{% for err in getFieldErrors(formName, fieldName) %}
        {{ err }}<br/>
{% endfor %}
```

In your template, just include the file
{% include "formErrors" with {'formName': 'aFormName', 'fieldName': 'fieldName'} %}
